#:kivy 2.1.0

WindowManager:
    MainWindow:
    SecondWindow:

<MainWindow>:
    name: "main"
    FloatLayout:
        size_hint: (1,1)
        pos_hint: {'x' : 0, 'y' : 0.8}
        # canvas:
        #     Color:
        #         rgba: 0, 0, 255, 0
            # Rectangle:
            #     color: 0, 0.533, 0.412, 0.8
        # FloatLayout:
        MenuBar:
            size_hint: (1, 0.2)
            pos_hint: ({'x': 1, 'y': 1})