#:kivy 2.1.0

# <MyManager>:
Screen:
    MDTopAppBar:
        id: toolbar
        title: "Multicast Mobile"
        screen_manager: screen_manager
        left_action_items:
            [
            ["home", lambda x: screen_manager.current("screen1"), "Home"]
            ]
        right_action_items:
            [
            ["magnify", lambda x: screen_manager.current("screen2"), "Search"],
            ["camera", lambda x: x, "Record"],
            ["account", lambda x: x, "Account"]
            ]

    MDNavigationLayout:
        x: toolbar.height
        ScreenManager:
            id: screen_manager
            HomeScreen:
                name: 'screen1'
                MDBoxLayout:
                    orientation: "vertical"
                    MDLabel:
                        text: "aaa"
                        halign: "center"
            
            WatchScreen:
                name: 'screen2'
                MDLabel:
                    text: "Hiiii"

        
        
    # MDNavigationLayout:
    #     ScreenNav:
    #         id: screen_manager
    #         Screen:
    #             name: 'main_screen'
    #             # MenuBar:
    #             ScrollView:
    #                 name: 'scrolling_view'
    #                 size_hint: (1, 0.8)
    #                 pos_hint: {'x' : 0, 'y' : 0}
    #                 # the scrolling layout must be referred to in main.py
    #                 # in order to add all online video streams
    #             FloatLayout:
    #                 id: scrolling_layout
    #                 size_hint: (1, 1.5)
    #                 text: 'hi'

    
    


<StreamButton>:
    # size_hint: (0.75, 0.2)
    size_hint: (0.2, 0.2)
    background_normal: ''
    background_color: (0, 0.533, 0.412, 1)

    # MenuBar:
    # on_press:
    #     root.manager.current: 'video_viewer'

<WatchScreen>:
    name: 'video_viewer'
    # MenuBar:

<AccountScreen>:
    name: 'account_screen'
    # MenuBar:
    Label:
        text: 'Hello, user!'
        color: 'black'
