[tool.briefcase]
project_name = "My Example App Project"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/sampleapp"
license = "BSD license"
author = 'Jane Developer'
author_email = "katmerrill7@gmail.com"

[tool.briefcase.app.sampleapp]
formal_name = "Sample App"
description = "My first application"
icon = "src/sampleapp/resources/sampleapp"
sources = ['src/sampleapp']
requires = [
]


[tool.briefcase.app.sampleapp.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.sampleapp.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.sampleapp.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.sampleapp.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.sampleapp.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.sampleapp.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.sampleapp.android]
requires = [
    'toga-android>=0.3.0.dev34'
]
